name: admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  supabase_flutter: ^2.9.0
  flutter_bloc: ^9.1.1
  image_picker: ^1.1.2
  go_router: ^15.1.2
  cached_network_image: ^3.4.1
  intl: 0.19.0
  archive: ^3.4.6
  dio: ^5.4.3
  file_saver: ^0.2.1
  excel: ^2.1.0
  file_picker: ^10.1.9
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
  skeletonizer: ^1.4.3
  icons_launcher: ^3.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  share_plus: ^7.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/

icons_launcher:
  image_path: 'assets/icon.png'
  platforms:
    android:
      enable: true
      image_path: 'assets/icon.png'
      
    
    web:
      enable: true
      image_path: 'assets/icon.png'
      